class Defaults {

  Defaults._();

  static const menu = <String, dynamic>{
     "1": [["Atole de amaranto",null,"Tamales de mole rojo y salsa verde",null,"Frijoles refritos","Totopos","Café","Fruta"],["Crema de chayote","Tallarines blancos","Milanesa de pollo empanizada","Lechuga, guacamole y limón",null,"Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Enchiladas verdes de pollo","Lechuga, queso y crema",null,null,"Té de limón","Fruta"]],
     "2": [["Licuado de plátano",null,"Sincronizadas de maíz","Verduras al vapor salsa de chipotle y aguacate","Frijoles refritos",null,"Té de manzanilla","Yogurt"],["Consomé con verduras y mollejas","Arroz blanco c/elote","Mole verde con pollo con calabacitas",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche\nYogurt","Granola","Tortitas de espinacas en caldillo de jitomate",null,"Frijoles guisados","Tortilla","Café","Galleta artesanal"]],
     "3": [["Leche",null,"Huevos motuleños","Salsa roja cocida","Frijoles guisados","Tortilla frita","Café","Fruta"],[null,"Arroz blanco","Cerdo en salsa verde con verdolagas",null,"Frijoles de la olla","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Hamburguesa de res con queso amarillo","Lechuga, chiles curados, jitomate, cebolla, cátsup y mayonesa",null,null,"Café","Papas fritas\nFruta"]],
     "4": [["Café con leche","Pan dulce","Picadillo de pollo","Chile en vinagre picado","Frijoles guisados","Tortilla","Te de manzanilla","Fruta"],["Sopa de verduras","Arroz rojo","Cecina de Yecapixtla","Guacamole, nopales y limón","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Gelatina","Molletes de jamón con queso","Pico de gallo",null,null,"Café","Fruta"]],
     "5": [["Leche","Cereal","Sopes de verduras","Salsa roja cocida, lechuga, queso y crema","Frijoles molidos",null,"Café","Fruta"],["Sopa de lentejas con tocino","Arroz rojo","Caldo de res con verduras","Cilantro, cebolla, limones y chile verde picado",null,"Tortilla","Agua de fruta","Chamoyada"],["Licuado de amaranto",null,"Tlacoyos","Nopales, cebolla con cilantro, salsa verde, queso","Frijoles guisados",null,"Café","Fruta"]],
     "6": [["Leche","Arroz con leche","Cuernitos de jamón","Lechuga, chiles curados, jitomate, aguacate y mayonesa","Frijoles molidos","Totopos","Té de hierbabuena",null],[null,"Arroz rojo","Pechuga a la plancha (con boleto)","Guacamole, limones y lechuga con pepinos","Frijoles molidos","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Espagueti a la boloñesa con queso","Ensalada dulce de col, zanahoria, pasas, nueces, y durazno","Frijoles guisados","Pan tipo baguette","Café","Fruta"]],
     "7": [["Leche\nYogurt",null,"Pancita de res (cuidar el caldo)","Orégano, limón, cebolla picada",null,"Tortilla","Café","Yakult"],["Aguacate","Arroz blanco c/plátano","Carne al pastor","Salsa roja cocida, limones, cebolla con cilantro","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Tacos dorados de zanahoria y queso blanco","Salsa ranchera, lechuga y crema, queso bco. rallado","Frijoles guisados",null,"Té de menta","Fruta"]],
     "8": [["Leche",null,"Alambre de vegetales (champiñones, chile pimiento, queso tocino, brócoli y calabacitas)","Salsa roja cocida","Frijoles guisados","Tortilla","Té de manzanilla","Kínder delice"],[null,"Arroz poblano","Bistec en salsa roja",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Pastel de papa, espinaca y queso Oaxaca","Salsa ranchera","Frijoles refritos","Tortilla","Té de frutas","Fruta"]],
     "9": [["Leche\nYogurt","Granola","Chorizo con calabacitas a la plancha",null,"Frijoles guisados","Tortilla","Té de cedrón","Gelatina"],[null,"Arroz blanco","Cerdo en chile morita",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Tortillas","Pocholas en salsa roja","Lechuga, jitomate, y pepino chiles en vinagre y limón","Frijoles guisados","Pan dulce","Café","Fruta"]],
    "10": [["Leche",null,"Mortadela","Salsa roja","Frijoles refritos","Tortilla","Café","Yogurt"],[null,"Tallarines rojos","Pollo adobado horneado","Limón, lechuga y zanahoria rallada salsa roja",null,"Tortilla","Agua de fruta","---"],["Leche","Cereal","Huevos a la mexicana","Salsa roja","Frijoles guisados","Tortilla","Café","Fruta"]],
    "11": [["Leche sabor chocolate","Obleas con semilla de calabaza (pepitorias)","Sándwich integral de jamón y queso","Lechuga, jitomate, cebolla, chile, mayonesa, aguacate","Frijoles refritos","Totopos","Té de limón","Fruta"],["Verduras a la mantequilla","Arroz","Discada","Salsa ranchera con limones","Frijoles guisados","Tortilla","Agua de fruta",null],["Leche",null,"Enjitomatadas de pollo","Lechuga, crema y queso","Frijoles refritos","Fruta","Té de canela","Yogurt"]],
    "12": [["Licuado de plátano",null,"Chilaquiles rancheros con pollo","Crema y queso, cebolla picada","Frijoles refritos","Totopos","Té de limón","Fruta"],["Codito rojo con crema",null,"Filete de pescado empanizado","Lechuga con zanahoria rallada, aguacate, limón y salsa valentina.","Frijoles refritos","Tortilla","Agua de fruta","Helado Sandwich"],["Leche","Yogurt","Fajitas de pollo con verdura","Salsa roja","Frijoles guisados","Tortilla","Té de cedrón","Fruta"]],
    "13": [["Leche","Cereal","Sopes de carne molida de res","Salsa roja cocida, lechuga, queso y crema","Frijoles refritos",null,"Té de hojas de naranjo","Fruta"],["Consomé con verduras con mollejas","Arroz blanco","Pollo en mole rojo",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche sabor chocolate",null,"Pizza (peperoni y hawaiana)","Cátsup y valentina, ensalada de espinacas","Frijoles refritos","Totopos","Café","Fruta\nChurros de amaranto"]],
    "14": [["Café con leche\nYogurt","Hojuelas de avena","Res molida con papas guisadas en salsa de chipotle",null,"Frijoles guisados","Tortilla","Té de hierbabuena","Fruta\nJugo tetra pack"],[null,"Arroz blanco","Cerdo tipo barbacoa","Nopales guisados, limón, salsa roja","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Quesadillas de queso Oaxaca","Salsa ranchera, lechuga y crema","Frijoles guisados",null,"Café","Fruta"]],
    "15": [["Leche",null,"Enmoladas con pollo","Queso, crema, lechuga","Frijoles de la olla",null,"Té de manzana","Fruta\nMini-gansito"],[null,"Arroz amarillo","Suadero encebollado con papas","Salsa roja cocida, rábanos, cilantro y limones","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Tortitas de pollo en salsa motuleña",null,"Frijoles refritos","Tortilla","Té de menta","Plátanos con crema"]],
    "16": [["Leche\nYogurt",null,"Hot cakes de avena",null,"Frijoles refritos con queso","Totopos","Café","Fruta"],["Sopa de papa","Arroz blanco","Conejo en adobo","Lechuga","Frijoles de olla","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Enchiladas mineras","Lechuga, crema y queso","Frijoles molidos",null,"Café","Fruta"]],
    "17": [["Café con leche","Pan dulce","Machaca de res con papas","Salsa roja cocida","Frijoles guisados","Tortilla","Té de canela",null],[null,"Arroz blanco con plátano","Asado de Pollo",null,"Frijoles guisados","Tortilla","Agua de fruta","Yogurt congelado"],["Leche","Gelatina","Tostadas de tinga de pollo","Lechuga","Frijoles refritos","Tostadas","Café","Fruta"]],
    "18": [["Licuado de avena","Brand fruit","Huevo a la mexicana seco","Chiles curados","Frijoles guisados","Tortilla","Té de frutas",null],["Sopa de calabacitas","Arroz rojo","Bistec en salsa verde con nopales",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Sincronizada de Maíz","Pico de gallo, aguacate, lechuga con pepino","Frijoles refritos",null,"Café","Fruta"]],
    "19": [["Café con leche","Yakult","Longaniza con cebolla y chile cuaresmeño","Salsa ranchera","Frijoles guisados","Tortilla","Té de manzanilla","Fruta"],[null,"Arroz verde","Pollo frito con verduras a la mantequilla","Chiles curados","Frijoles de la olla","Tortilla","Agua de fruta","Fruta"],["Leche","Gomitas azucaradas","Poblanitas con pollo",null,"Frijoles refritos","Baguette","Té de hojas de naranjo",null]],
    "20": [["Leche\nYogurt",null,"Mortadela empanizada","Salsa roja","Frijoles refritos","Tortilla","Café","Fruta"],[null,"Arroz blanco","Caldo Tlalpeño de pollo","Limón, cebolla, cilantro, chile picado","Frijoles guisados","Tortilla","Agua de fruta","Paleta helada de crema"],["Leche\nCereal",null,"Molletes (frijoles con queso)","Pico de gallo",null,null,"Café","Fruta"]],
    "21": [["Leche",null,"Omelette de espinacas con queso panela y queso Oaxaca","Salsa ranchera","Frijoles guisados","Tortilla","Café","Jugo tetra pack"],[null,"Espaguetti blanco","Cecina de cerdo adobada","Guacamole, nopales y limones","Frijoles charros","Tortilla","Agua de fruta","Fruta"],["Leche\nYogurt","Granola","Enfrijoladas rellenas de jamón con queso","Lechuga, crema","Salsa de chiupotle",null,"Té de limón","Fruta"]],
    "22": [["Leche\nYogurt",null,"Chilaquiles rojos con pollo","Queso, crema","Frijoles refritos","Baguete","Café","Fruta"],["Sopa de habas con nopales","Espagueti rojo con queso","Pollo frito a la naranja","Salsa chipotle",null,"Tortilla","Agua de fruta","Fruta"],["Leche","Cereal sabor chocolate","Tortita campirana en caldillo de jitomate",null,"Frijoles guisados","Tortilla","Té limón","Fruta\nGelatina"]],
    "23": [["Leche","Galleta artesanal con chispas de chocolate","Burritos de jamón y queso con frijoles molidos","Salsa ranchera",null,null,"Té de hojas de guayabo","Fruta"],["Sopa de pasta","Arroz blanco","Cerdo en guajillo con papas y nopales",null,"Frijoles de la olla","Tortilla","Agua de fruta","Churritos de amaranto"],["Leche","Cereal","Tinga de res","Lechuga, queso y crema","Frijoles refritos","Tostada","Café","Fruta"]],
    "24": [["Leche",null,"Quesadillas de queso Oaxaca con champiñones","Salsa ranchera, lechuga y crema","Frijoles guisados",null,"Té de hierbabuena","Gelatina"],[null,"Arroz blanco","Mole de olla",null,"Frijoles guisados","Tortilla","Agua de fruta","Palanqueta"],["Malteada de fresa",null,"Chorizo c/papas","Salsa verde cocida","Frijoles molidos","Tortilla","Café","Fruta"]],
    "25": [["Licuado de fruta",null,"Verduras gratinadas horneadas con fajitas de pollo","Salsa roja","Frijoles guisados","Tortilla","Té de canela","Bubulubu"],[null,"Arroz rojo con plátano","Cecina de res","Guacamole, nopales, limones","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Chocohojuelas","Pozole verde estilo guerrero","Lechuga, limón, rábanos, cebolla, chile piquín, orégano y aguacate",null,"Tostadas","Café",null]],
    "26": [["Leche","Cereal","Huevo con coliflor","Salsa roja","Frijoles guisados","Tortilla","Café","Fruta"],["Caldo de camarón","Arroz amarillo","Ceviche de pescado, pulpo y camarón","Limón, aguacate y salsa valentina",null,"Tostadas","Agua de fruta","Paleta de agua"],["Leche",null,"Huaraches de carne molida y vegetales","Lechuga, queso, crema y salsa roja","Frijoles refritos",null,"Té de manzanilla","Gelatina"]],
    "27": [["Café con leche","Repostería","Papas con rajas y queso Oaxaca","Salsa verde, queso y crema","Frijoles guisados","Tortilla","Té de piña","Fruta"],[null,"Arroz rojo","Milanesa de pollo","Guacamole, lechuga y limones","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Hot Dog: Salchicha frita (1 pieza)","Jitomate, cebolla y chile picado, cátsup, mayonesa","Frijoles refritos con queso","Totopos","Café","Fruta"]],
    "28": [["Leche","Cereal","Picadillo de res","Chiles en vinagre","Frijoles guisados","Tortilla","Café","Yakult"],[null,"Arroz blanco","Pavo deshebrado frito con cebolla","Ensalada de lechuga y pepino, zanahoria rallada y limón",null,"Tortilla","Agua de fruta","Fruta"],["Atole de arroz",null,"Quesadillas de Choriqueso (queso manchego y Oaxaca)","Salsa roja cocida, lechuga con jitomate","Frijoles guisados",null,"Té de azahares","Fruta"]],
    "29": [["Leche\nYogurt",null,"Chilaquiles de mole con pollo (molequiles)","Queso y crema","Frijoles refritos","Baguette",null,"Té de cedrón"],[null,"Arroz amarillo","Cerdo en salsa de tamarindo",null,"Puré de papa","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Alambre de res","Salsa roja cocida, limón y cebolla con cilantro","Frijoles guisados","Tortilla","Té de limón","Fruta"]],
    "30": [["Malteada de vainilla",null,"Sincronizadas de maíz","Verduras al vapor, salsa de chipotle y aguacate","Frijoles refritos",null,"Té de manzanilla","Yogurt"],[null,"Arroz rojo","Pollo en mole rojo",null,"Frijoles guisados","Tortilla","Agua de fruta","Cacahuates artesanales"],["Leche",null,"Hamburguesa","Chiles curados, lechuga, jitomate, cebolla, cátsup y mayonesa, mostaza",null,"Gelatina de agua","Café","Papas fritas"]],
    "31": [["Leche con chocolate",null,"Sopes de verduras","Salsa roja cocida, lechuga, queso y crema","Frijoles refritos",null,"Café","Mazapán"],[null,"Arroz blanco","Suadero con papas y cebolla","Salsa roja, limón y cilantro","Frijoles guisados","Tortilla","Agua de fruta","Pepitas de calabaza"],["Leche","Cereal","Burritos de jamón y queso","Salsa chipotle\nEnsalada de lechuga con pepino","Frijoles molidos",null,"Café","Fruta"]],
    "32": [["Café con leche","Pan dulce","Pollo con brócoli en salsa roja",null,"Frijoles guisados","Tortilla","Té de limón","Fruta"],["Sopa de papa","Arroz amarillo","Cecina adobada de cerdo","Guacamole, limón, ensalada de rábano, cebolla y nopales","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Pan tostado c/mermelada (2 piezas)","Quesadillas poblanas con tortillas de maíz (queso Oaxaca, queso bco. y chile poblano)","Salsa ranchera, lechuga","Frijoles guisados",null,"Té de guayaba","Fruta"]],
    "33": [["Atole de arroz",null,"Cuernitos de jamón","Lechuga, chiles curados, jitomate, aguacate y mayonesa","Frijoles molidos",null,"Café","Fruta"],["Sopa azteca","Arroz blanco","Tortas de papa rallada con queso blanco en caldillo de jitomate",null,"Frijoles guisados","Tortilla","Agua de fruta","Yogurt congelado"],["Leche","Cereal","Enchiladas verdes de pollo","Lechuga, queso y crema","Frijoles guisados",null,"Té de canela","Fruta"]],
    "34": [["Leche\nYogurt","Granola","Chilaquiles rojos con pollo","Queso y crema","Frijoles refritos","Pan de baguette","Té de canela","Fruta"],[null,"Arroz rojo","Tinga de pollo","Queso, crema, lechuga","Frijoles con longaniza","Tostadas","Agua de fruta","Fruta"],["Leche sabor chocolate",null,"Pizza (Peperoni y hawaiana)","Cátsup, salsa valentina","Frijoles refritos","Totopos","Té de menta","Flan"]],
    "35": [["Leche\n",null,"Ejotes con huevo","Salsa roja cocida","Frijoles guisados","Tortilla","Té de cedrón","Jugo tetra pack"],["Espagueti blanco",null,"Pechuga de pollo a la plancha","Guacamole, limones y lechuga","Frijoles refritos","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Volován hawaiano","Cátsup, salsa valentina","Frijoles refritos","Totopos","Café","Gelatina de leche"]],
    "36": [["Leche","Cereal","Calabacitas a la mexicana con granos de elote","Crema y queso","Frijoles guisados","Tortilla","Te de frutas","Fruta"],[null,"Arroz blanco","Res en mole de olla","Limón, chile y cebolla picados","Frijoles guisados con chorizo","Tortillas","Agua de fruta","Fruta"],["Licuado de amaranto",null,"Tlacoyos","Nopales, cebolla con cilantro, salsa verde, queso","Frijoles guisados",null,"Café","Gelatina con fruta"]],
    "37": [["Leche",null,"Chilaquiles rojos con pollo","Crema y queso","Frijoles refritos","Baguete","Café","Yogurt"],["Crema de zanahoria con bombitos","Espagueti blanco","Pollo en salsa verde con nopales y champiñones",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta en almíbar"],["Licuado de fresa",null,"Molletes","Pico de gallo",null,null,"Café","Yogurt\nFruta"]],
    "38": [["Atole de avena",null,"Enjitomatadas de queso manchego","Lechuga, crema","Frijoles refritos",null,"Té de hojas de naranjo","Gelatina"],["Sopa de alverjón","Arroz blanco con plátano","Cerdo estilo minero",null,null,"Tortilla","Agua de fruta","Paleta de yogurt"],["Leche","Cereal","Estofado de pollo","Chiles curados","Frijoles guisados","Telera de 60 g","Te de manzanilla","Fruta"]],
    "39": [["Leche sabor chocolate",null,"Sándwich integral de jamón y queso","Lechuga, jitomate, cebolla, chile, mayonesa, aguacate","Frijoles refritos","Totopos","Té de limón","Fruta"],[null,"Arroz rojo","Pechuga a la plancha","Guacamole, limones y lechuga con pepinos","Frijoles molidos","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Memelas campechanas","Salsa roja","Frijoles refritos","Lechuga, queso, crema","Té de piña","Gelatina de agua"]],
    "40": [["Café con leche","Repostería","Carne molida con nopales","Salsa roja","Frijoles guisados","Tortilla","Té de manzanilla","---"],["Arroz blanco","Ensalada de lechuga, zanahoria, arándanos y nuez","Chuleta a la BBQ",null,"Sopa de lentejas con tocino","Tortilla","Agua de fruta","Fruta"],["Licuado de fruta",null,"Espagueti a la boloñesa",null,"Frijoles guisados","Baguette","Té de ponche de frutas","Ensalada dulce de col,\nzanahoria y piña"]],
    "41": [["Leche","Cereal","Huevo con verdolaga","Salsa roja","Frijoles guisados","Tortilla","Té de hierbabuena","Fruta"],["Arroz blanco con plátano","Consomé con verduras","Pollo en salsa roja de guajillo con nopales",null,"Frijoles guisados","Tortilla","Agua de fruta","Churritos de amaranto"],["Leche","Cereal","Longaniza con papas y nopales","Salsa de chile de árbol","Frijoles refritos","Tortilla","Café","Fruta"]],
    "42": [["Atole de amaranto",null,"Tamales de rajas y salsa verde",null,"Frijoles refritos","Totopos","Café","Yakult"],[null,"Arroz blanco","Bistec encebollado con papas","Salsa verde\nEnsalada de lechuga, pepino y limón","Frijoles guisados","Tortilla","Agua de fruta","Helado de crema en vaso"],["Leche",null,"Quesadillas de queso Oaxaca","Salsa ranchera, lechuga, crema","Frijoles guisados",null,"Té de hierbabuena","Fruta"]],
    "43": [[null,"Yogurt","Marinas de pollo con mole",null,"Frijoles refritos c/queso","Totopos","Café","Fruta"],[null,"Arroz blanco","Birria de res","Cebolla y chile picado, cilantro y limón","Frijoles de la olla","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Sincronizada de maíz","Pico de gallo y aguacate","Frijoles refritos",null,"Café","Ate"]],
    "44": [["Leche","Cereal","Burritos de jamón y queso","Salsa ranchera","Frijoles molidos",null,"Té de hojas de limón","Fruta"],["Consomé con verduras y mollejas","Codito a la hawaiana","Pollo en cazuela de adobo con papa",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Café con leche",null,"Calabacitas con queso a la mantequilla","Salsa roja\nCrema","Frijoles refritos","Tortilla","Te de frutas","Fruta\nKínder delice"]],
    "45": [["Leche",null,"Tortitas de pollo con espinaca en caldillo de jitomates",null,"Frijoles guisados","Tortilla","Café","Tarta de fruta"],["Verduras al vapor","Arroz blanco","Pierna enchilada","Salsa ranchera guisada","Frijoles de la olla","Tortilla","Agua de fruta","Paleta de crema"],["Atole vainilla",null,"Pastel de papa con chorizo","Salsa verde cocida","Frijoles refritos","Tortilla","Café","Fruta"]],
    "46": [["Leche","Gelatina de agua","Huevo con coliflor","Salsa roja","Frijoles guisados","Tortilla","Café","Fruta"],[null,"Arroz verde","Cerdo en salsa verde con verdolagas",null,"Frijoles de olla","Tortilla","Agua de fruta","Gomitas de mango enchilado"],["Leche",null,"Quesadillas de queso con espinacas","Salsa de chile de árbol Ensalada dulce de zanahoria rallada, betabel rallado, piña, nuez y pasas","Frijoles guisados",null,"Té de hierbabuena","Fruta"]],
    "47": [["Leche","Cereal","Picadillo de res","Chiles en vinagre","Frijoles guisados","Tortilla","Te de cedrón","Fruta"],["Aguacate","Codito rojo","Conejo veloz","Ensalada de lechuga con pepino, limones, salsa verde con chile habanero","Frijoles guisados","Tortilla","Agua de fruta","Fruta en almíbar"],["Leche","Barrita Brand fruit","Tortitas de pollo en salsa verde con calabacitas","Ensalada de espinaca con tocino frito, ajonjolí y aceite de oliva.","Frijoles refritos","Tortilla","Café","Fruta"]],
    "48": [["Café\nYogurt",null,"Hot cakes con arándano y piña","Miel de maple","Frijoles refritos","Totopos","Leche","Fruta"],["Sopa de verduras","Arroz rojo","Pollo en crema de chipotle con champiñones",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Alitas a BBQ","Ensalada de zanahoria y pepino","Frijoles refritos","Totopos","Té canela","Fruta"]],
    "49": [["Malteada de fresa",null,"Sopa azteca con bisteck","Queso, crema","Frijoles de la olla",null,"Café","Fruta\nJugo tetra pack"],[null,"Arroz blanco c/plátano","Carne al pastor","Salsa roja cocida, limones, cebolla con cilantro, ensalada de lechuga con pepino","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Chalupas de pollo","Lechuga, queso y crema\nSalsa verde cocida","Frijoles molidos","Cacahuates","Té de manzanilla","Fruta"]],
    "50": [["Licuado de guayaba",null,"Quesadillas de queso panela y oaxaca con champiñones","Salsa ranchera lechuga y crema","Frijoles guisados",null,"Café","Fruta"],[null,"Arroz blanco","Estofado de res","Cebolla picada y chile picada","Frijoles de olla","Tortilla","Agua de fruta","Fruta"],["Café con leche","Repostería","Salpicón de pollo","Chiles curados, crema, queso","Frijoles refritos","Tostadas","Te de limón helado","Fruta"]],
    "51": [["Leche",null,"Huevo con jamón","Salsa chipotle","Frijoles refritos con queso","Tortilla","Te de cedrón","Cereal de arroz inflado sabor chocolate"],["Sopa de papa","Arroz amarillo","Albóndigas de pollo en salsa verde",null,"Frijoles guisados","Tortilla","Agua de fruta","Yogurt congelado"],["Leche sabor vainilla",null,"Pambazos de papas con longaniza bañados en salsa de guajillo.","Queso, crema, salsa verde cocida y lechuga","Queso, crema, salsa verde cocida y lechuga",null,"Café","Fruta"]],
    "52": [["Malteada de chocolate",null,"Chilaquiles verdes con pollo","Queso, crema","Frijoles refritos","Baguette","Café","Fruta"],["Sopa de pasta","Arroz blanco","Cecina de res","Guacamole, limones y nopales","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Tacos dorados de zanahoria con betabel y queso","Lechuga, salsa roja cocida, crema y queso","Frijoles guisados","Gelatina de leche","Té de hierbabuena","Plátanos con crema"]],
    "53": [["Malteada de fresa",null,"Enmoladas con queso","Crema, lechuga","Frijoles de la olla",null,"Té de manzanilla","Fruta"],[null,"Arroz blanco","Cerdo en salsa roja con verdolagas",null,"Frijoles de la olla","Tortilla","Agua de fruta","Fruta"],["Agua de fruta",null,"Pozole rojo con carne de cerdo","Orégano, lechuga, rábano, cebolla, aguacate y limón",null,"Tostadas","Café","Refresquito Pascual"]],
    "54": [["Café con leche","Pan dulce","Pollo con espinacas en salsa verde",null,"Frijoles guisados","Tortilla","Té de guayaba","Fruta"],["Caldo de camarón","Arroz amarillo","Ceviche con pescado, pulpo y camarón","Limón, aguacate y salsa valentina",null,"Tostadas","Agua de Fruta","Fruta"],["Leche","Cereal","Memelas campechanas","Queso, crema, lechuga, salsa roja cocida","Frijoles refritos",null,"Té negro","Fruta"]],
    "55": [["Leche",null,"Huevo con chorizo","Salsa ranchera","Frijoles guisados","Tortilla","Té de canela","Fruta\nGomitas azucaradas (35 g)"],[null,"Codito hawaiano","Pollo en chile pasilla",null,"Frijoles guisados","Tortilla","Agua de Fruta","Paleta de yogurt"],["Leche",null,"Alambre de vegetales","Salsa roja cocida","Cacahuates enchilados","Frijoles refritos","Té de limon","Fruta"]],
    "56": [["Leche","Cereal","Chuleta a la cacerola con verduras en salsa roja",null,null,"Frijoles guisados","Tortilla","Café\nJugo tetrapack"],[null,"Espagueti rojo","Verduras a la mantequilla, gratinadas con fajitas de pollo","Salsa roja","Frijoles guisados","Tortilla","Agua de fruta","Duraznos en almíbar"],["Leche",null,"Quesadillas de champiñones","Salsa roja\nLechuga y crema","Frijoles guisados",null,"Café","Fruta\nRocko"]]
  };

  static final inicio = DateTime.utc(2022, 7, 31);
  static const int startingDay = 35;
  static final fin = DateTime.utc(2022, 12, 18);

  static const lastUpdateMenu = 2022052901;
  static const lastUpdateFechas = 2022041902;

  static const info = <String, dynamic>{};

  static const lastUpdateInfo = 2020022101;
}
