class Defaults {

  Defaults._();
  
  static const menu = <String, dynamic>{
   "0":[<String>[],<String>[],["Leche","Cereal","Enchiladas verdes de pollo","Lechuga, queso y crema","Frijoles guisados",null,"Té de limón","Fruta"]],
   "1":[["Champurrado",null,"Tamales de mole rojo y salsa verde",null,"Frijoles refritos","Totopos","Café","Fruta"],["Crema de chayote","Tallarines blancos","Milanesa de res empanizada","Lechuga, guacamole y limón","Frijoles de la olla","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Enchiladas verdes de pollo","Lechuga, queso y crema","Frijoles guisados",null,"Té de limón","Fruta"]],
   "2":[["Licuado de plátano",null,"Sincronizadas de maíz","Verduras al vapor salsa de chipotle y aguacate","Frijoles refritos",null,"Té de manzanilla","Yogurt con granola"],["Consomé con verduras y mollejas","Arroz blanco c/salchicha","Mole verde con pollo con calabacitas",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche\nYogurt","Granola","Tortitas de espinacas en caldillo de jitomate",null,"Frijoles guisados","Tortilla","Té de fruta","Fruta"]],
   "3":[["Leche","Cereal","Sopes de verduras","Salsa roja cocida, lechuga, queso y crema","Frijoles molidos",null,"Café","Fruta"],["Sopa azteca","Arroz blanco","Cerdo en salsa verde con verdolagas",null,"Frijoles de la olla","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Hamburguesa de res con queso amarillo","Lechuga, chiles curados, jitomate, cebolla, cátsup, mostaza y mayonesa",null,null,"Té de azahares","Papas fritas\nFruta"]],
   "4":[["Café con leche","Pan dulce","Sopa minestrone con pollo","Chiles en vinagre picados","Frijoles guisados","Tortilla","Té de manzanilla","Fruta"],["Sopa de verduras","Arroz rojo","Cecina de Yecapixtla con boleto en banda","Guacamole, nopales, crema y limón","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Volován hawaiano con queso oaxaca","Salsa valentina\nSalsa cátsup","Frijoles refritos","Totopos","Té de canela","Fruta\nGelatina"]],
   "5":[["Leche",null,"Huevos motuleños","Salsa roja cocida","Frijoles guisados","Tortilla frita","Té de naranjo","Fruta"],["Sopa de lentejas con nopales","Arroz rojo","Pavo desmenuzado con cebolla","Ensalada de lechuga con pepinos, zanahoria rallada, limones, salsa roja",null,"Tortilla","Agua de fruta","Chamoyada"],["Leche",null,"Espagueti a la boloñesa","Ensalada dulce de col, zanahoria y piña","Frijoles guisados","Pan tipo baguette","Café","Galleta artesanal"]],
   "6":[["Leche","Arroz con leche","Cuernitos de jamón","Lechuga, chiles curados, jitomate, aguacate y mayonesa","Frijoles molidos","Totopos","Té de hierbabuena","Gomitas azucaradas"],[null,"Arroz rojo","Pechuga a la plancha (con boleto en bandas)","Guacamole, limones y lechuga con pepinos","Frijoles molidos","Tortilla","Agua de fruta","Fruta picada"],["Licuado de amaranto",null,"Tlacoyos","Nopales, cebolla, cilantro, salsa verde, queso","Frijoles guisados",null,"Café","Fruta"]],
   "7":[["Leche\nYogurt","Granola","Pancita de res","Orégano, limón, cebolla picada","Frijoles guisados","Tortilla","Café","Yakult"],["Ensalada de pepino, aguacate rebanado","Arroz blanco c/plátano","Carne al pastor","Salsa roja cocida, limones, cebolla, rábanos y cilantro","Frijoles guisados","Tortilla","Agua de fruta","Paleta helada de agua"],["Leche","Cereal","Tacos dorados de zanahoria y queso bco.","Salsa ranchera, lechuga y crema, queso bco. rallado","Frijoles guisados",null,"Té de menta","Fruta"]],
   "8":[["Atole de avena",null,"Enfrijoladas con queso manchego","Salsa roja cocida, lechuga, queso y crema","Frijoles guisados",null,"Café","Fruta"],["Sopa de chayote","Arroz poblano","Bistec en salsa roja",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Pastel de papa, espinaca y queso Oaxaca","Salsa ranchera","Frijoles refritos","Tortilla","Té de manzanilla","Fruta\nKínder Delice"]],
   "9":[["Leche\nYogurt","Granola","Chorizo con calabacitas a la plancha",null,"Frijoles guisados","Tortilla","Té cedrón","Tartas de frutas"],["Sopa de pasta","Arroz blanco","Cerdo en chile morita",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Pocholas","Lechuga, jitomate y pepino, chiles en vinagre, limón","Frijoles guisados",null,"Café","Fruta"]],
   "10":[["Leche",null,"Queso empanizado","Salsa chipotle, lechuga","Frijoles refritos","Tortilla","Café","Yogurt con granola"],["Sopa de alverjón con nopales","Tallarines rojos","Pollo adobado horneado","Limón, lechuga y zanahoria rallada, salsa roja",null,"Tortilla","Agua de fruta","Churritos de amaranto"],["Atole de avena",null,"Enjitomatadas de queso Oaxaca","Lechuga, crema y queso","Frijoles refritos",null,"Té de canela","Yogurt con granola"]],
   "11":[["Leche","Cereal","Chuleta fresca en salsa roja con papas",null,"Frijoles guisados","Tortilla","Té de limón","Fruta"],["Verduras a la mantequilla","Arroz","Discada","Salsa ranchera con limones","Frijoles guisados","Tortilla","Agua de fruta","Palanqueta de cacahuate"],["Leche","Cereal","Huevo con jamón","Salsa roja","Frijoles guisados","Tortilla","Café","Fruta"]],
   "12":[["Licuado de plátano con chocolate",null,"Chilaquiles rancheros con pollo","Crema, queso y cebolla picada","Frijoles guisados","Baguette","Café","Fruta"],["Sopa de verduras","Arroz rojo","Filete de pescado empanizado","Lechuga con zanahoria rallada, aguacate, limón y salsa de chipotle","Frijoles refritos","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Fajitas de pollo con verdura","Salsa de roja","Frijoles guisados","Tortilla","Té de frutas","Fruta"]],
   "13":[["Leche","Cereal","Sopes de carne molida de res","Salsa roja cocida, lechuga, queso y crema","Frijoles refritos",null,"Té de hojas de naranjo","Fruta"],["Consomé con verduras con mollejas","Arroz a la mexicana","Pollo en mole rojo",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche sabor chocolate",null,"Pizza (pepperoni y hawaiana)","Cátsup y valentina","Frijoles refritos","Totopos","Café","Fruta\nFlan"]],
   "14":[["Café con Leche\nYogurt","Granola","Res molida con papas guisadas en salsa de chipotle",null,"Frijoles guisados","Tortilla","Té de hierbabuena","Fruta\nJugo tetra pack"],[null,"Arroz blanco","Cerdo tipo barbacoa","Ensalada de lechuga, pepino y rábano. Limón. Chile en vinagre.","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Pambazos de papa con chorizo cubiertos de chile guajillo","Salsa verde en crudo, lechuga, crema, queso blanco rallado","Frijoles guisados",null,"Café","Fruta"]],
   "15":[["Leche\nYogurt",null,"Hot cakes sabor chocolate",null,"Frijoles refritos con queso","Totopos","Café","Fruta"],["Sopa de zanahoria y ejote","Arroz amarillo","Suadero encebollado con papas","Salsa roja cocida, rábanos y limones","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Polvorones","Tortitas de pollo en salsa motuleña",null,"Frijoles refritos","Tortilla","Té de menta","Fruta"]],
   "16":[["Leche\nYogurt","Granola","Mortadela empanizada","Salsa roja","Frijoles guisados","Tortilla","Café","Fruta"],["Sopa de papa","Arroz blanco","Conejo en adobo","Cebolla morada en rodajas","Frijoles de olla","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Enchiladas mineras","Lechuga, queso y crema","Frijoles molidos",null,"Café","Fruta"]],
   "17":[["Café con leche","Pan dulce","Machaca de res con papas","Salsa roja cocida","Frijoles guisados","Tortilla","Té de canela","Fruta"],["Crema de zanahoria","Arroz blanco con plátano","Asado de pollo",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Tostadas de pavo a la crema","Salsa chipotle","Frijoles refritos","Tostadas","Café","Fruta"]],
   "18":[["Leche",null,"Enmoladas con pollo","Queso, crema, lechuga","Frijoles de la olla",null,"Café","Fruta\nCanelitas"],["Sopa de calabacitas","Arroz rojo","Bistec en salsa verde con nopales",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Sincronizada de maíz","Pico de gallo, aguacate, lechuga con pepino","Frijoles refritos",null,"Café","Gelatina"]],
   "19":[["Café con leche","Yakult","Longaniza con cebolla y chile cuaresmeño","Salsa ranchera","Frijoles guisados","Tortilla","Té de manzanilla","Fruta"],["Sopa de verduras","Arroz rojo","Mojarra frita al mojo de ajo","Lechuga, pepinos, limón y salsa roja","Frijoles guisados","Tortilla","Agua de fruta","Yogurt congelado"],["Leche","Barrita de amaranto sabor fresa y chocolate","Poblanita con pollo",null,"Frijoles refritos","Baguette","Te hojas de naranjo",null]],
   "20":[["Licuado de avena",null,"Huevo a la mexicana seco","Chiles curados","Frijoles guisados","Tortilla","Té de frutas","Plátanos con crema"],[null,"Arroz blanco","Caldo tlalpeño de pollo","Limón, cebolla, cilantro, chile picado","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche\nYogurt","Granola","Molletes","Pico de gallo",null,null,"Café","Fruta"]],
   "21":[["Leche","Cereal","Omelette de espinacas con queso panela y queso Oaxaca","Salsa ranchera","Frijoles guisados","Tortilla","Café","Jugo tetra pack"],[null,"Espagueti blanco","Cecina de cerdo adobada","Guacamole, nopales y limones","Frijoles charros","Tortilla","Agua de fruta","Fruta"],["Leche\nYogurt","Granola","Coctel de champiñones y setas","Aguacate, salsa valentina, limón",null,"Galleta salada","Té de limón","Fruta"]],
   "22":[["Leche\nYogurt","Granola","Chilaquiles rojos con pollo","Queso, crema","Frijoles refritos","Baguete","Café","Fruta"],["Sopa de habas con nopales","Espagueti rojo con queso","Pollo frito a la naranja","Salsa chipotle",null,"Pan de sal","Agua de fruta","Fruta"],["Leche","Barra de hojuelas","Tortita campirana en caldillo de jitomate",null,"Frijoles guisados","Tortilla","Té limón","Fruta\nGelatina"]],
   "23":[["Leche","Galletas artesanales con chispas de chocolate","Burritos de jamón y queso con frijoles molidos","Salsa ranchera",null,null,"Té de hojas de guayabo","Fruta"],["Sopa de pasta","Arroz blanco","Cerdo en guajillo",null,"Frijoles de la olla","Tortilla","Agua de fruta","Churritos de amaranto"],["Leche","Cereal","Tinga de res","Lechuga, queso, crema","Frijoles refritos","Tostada","Café","Fruta"]],
   "24":[["Leche",null,"Quesadillas de queso y champiñones","Salsa ranchera, lechuga y crema","Frijoles guisados",null,"Té de hierbabuena","Gelatina"],["Consomé con verduras y mollejas","Arroz blanco","Res entomatada",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Té de fruta",null,"Chorizo c/papas","Salsa verde cocida","Frijoles molidos","Tortilla","Café","Fruta"]],
   "25":[["Licuado de fruta",null,"Verduras gratinadas horneadas","Salsa roja","Frijoles guisados","Tortilla","Té de canela","Barrita integral de fresa"],["Sopa de papa","Arroz rojo con plátano","Cecina de res","Guacamole, nopales, limones","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Chocohojuelas","Pozole verde estilo guerrero","Lechuga, limón, rábanos, cebolla, chile piquín, orégano, aguacate","Frijoles refritos","Tostadas","Café","Fruta"]],
   "26":[["Leche","Cereal","Huevo con salchicha","Salsa roja","Frijoles guisados","Tortilla","Café","Fruta"],[null,"Codito rojo","Ceviche de pescado, pulpo y camarón","Lechuga, pepino, limón y salsa valentina, aguacate",null,"Tostadas","Agua de fruta","Paleta de agua"],["Leche",null,"Huaraches de carne molida y vegetales","Lechuga, queso, crema, salsa roja","Frijoles refritos",null,"Té de manzanilla","Gelatina"]],
   "27":[["Café con leche","Repostería","Papas con rajas y queso Oaxaca","Salsa verde, queso y crema","Frijoles guisados","Tortilla","Té de piña","Fruta"],["Sopa de fideo","Arroz rojo","Milanesa de pollo","Guacamole, lechuga y limones","Frijoles guisados","Tortilla","Agua de fruta","Fruta picada"],["Leche","Cereal","Hot dog (1 pieza)","Jitomate, cebolla y chile picado, cátsup, mayonesa","Frijoles refritos con queso","Totopos","Té de piña","Plátanos con crema"]],
   "28":[["Leche","Cereal","Picadillo de res","Chiles en vinagre","Frijoles guisados","Tortilla","Café","Jugo tetra pack"],["Sopa azteca","Arroz blanco","Pavo deshebrado frito con cebolla","Ensalada de lechuga y pepino y zanahoria rallada, salsa roja cocida, limón","Frijoles charros","Tortilla","Agua de fruta","Fruta"],["Atole de arroz",null,"Quesadillas de choriqueso (queso manchego y Oaxaca)","Salsa roja cocida, lechuga con jitomate","Frijoles guisados",null,"Té de azahares","Fruta"]],
   "29":[["Leche","Yogurt\n","Chilaquiles de mole con pollo (molequiles)","Granola","Queso y crema","Frijoles refritos","Té de naranjo","Té cedron"],["Sopa de chayote y zanahoria","Arroz amarillo","Cerdo a la naranja",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Alambre de res","Salsa roja cocida, cilantro, limón, rábanos y cebolla","Frijoles guisados","Tortilla","Té de limón","Fruta\nAmaranto sabor chocolate"]],
   "30":[["Licuado de plátano",null,"Sincronizadas de maíz","Verduras al vapor salsa de chipotle y aguacate","Frijoles refritos",null,"Té de manzanilla","Yogurt con granola"],["Sopa de fideo","Arroz rojo","Pollo en mole rojo",null,"Frijoles guisados","Tortilla","Agua de fruta","Cacahuates artesanales"],["Malteada de vainilla",null,"Hamburguesa vegetariana","Chiles curados, lechuga, jitomate, cebolla, cátsup, mostaza y mayonesa","Frijoles molidos",null,"Café","Papas fritas\nFruta"]],
   "31":[["Leche con chocolate",null,"Sopes de verduras","Salsa roja cocida, lechuga, queso y crema","Frijoles refritos",null,"Café","Mazapán"],[null,"Arroz blanco","Albóndigas de res en chipotle",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche\nYogurt","Granola","Chayotes rellenos con jamón y queso","Salsa roja","Frijoles refritos","Pan de sal","Café","Fruta"]],
   "32":[["Café con leche","Pan dulce","Pollo con brócoli en salsa roja","Chiles en vinagre","Frijoles guisados","Tortilla","Té de limón","Fruta"],["Sopa de papa","Arroz verde","Cecina adobada de cerdo","Guacamole, nopales, limón","Frijoles guisados","Tortilla","Agua de fruta","Chamoyada"],["Leche","Pan tostado c/mermelada","Quesadillas poblanas (queso Oaxaca, queso bco. y chile poblano)","Salsa ranchera, lechuga","Frijoles guisados",null,"Café","Fruta"]],
   "33":[["Leche","Arroz con leche","Cuernitos de jamón","Lechuga, chiles curados, jitomate, aguacate y mayonesa","Frijoles molidos","Totopos","Té hierbabuena","Fruta"],["Sopa de nopales","Arroz blanco","Tortas de papa rallada con queso blanco","Ensalada de espinaca, ajonjolí y pasas","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Enchiladas verdes de pollo","Lechuga, queso y crema","Frijoles guisados",null,"Té de azahares","Fruta"]],
   "34":[["Leche\nYogurt","Granola","Chilaquiles de mole con pollo (molequiles)","Queso y crema","Frijoles refritos",null,"Café","Fruta"],["Crema de cilantro","Arroz rojo","Tinga de pavo","Queso, crema, lechuga","Frijoles con longaniza","Tostadas","Agua de fruta","Fruta"],["Leche sabor chocolate",null,"Pizza Peperoni y Hawaiana","Cátsup, salsa valentina","Frijoles refritos","Totopos","Café","Fruta\nFlan"]],
   "35":[["Leche\nCereal",null,"Ejotes con huevo","Salsa roja cocida","Frijoles refritos","Tortila","Té cedrón","Yakult"],[null,"Sopa azteca","Pechuga de pollo a la plancha","Guacamole, limones y lechuga","Frijoles refritos","Tortilla","Agua de fruta","Fruta picada"],["Leche",null,"Torta de jamón y queso Oaxaca","Chiles curados, lechuga, mayonesa, aguacate, jitomate y cebolla","Frijoles refritos",null,"Té de canela","Fruta\nGelatina de leche"]],
   "36":[["Leche","Cereal","Calabacitas a la mexicana con granos de elote","Crema y queso","Frijoles guisados","Tortilla","Té de frutas","Fruta"],["Sopa de pasta","Arroz blanco","Res en mole de olla","Limón, chile y cebolla picados","Frijoles guisados con chorizo","Tortillas","Agua de fruta","fruta"],["Licuado de amaranto",null,"Tlacoyos","Nopales, cebolla, cilantro, salsa verde, queso","Frijoles guisados",null,"Café","Fruta\nGelatina"]],
   "37":[["Leche",null,"Chilaquiles rojos con pollo","Crema y queso","Frijoles refritos","Baguette","Café","Yogurt con granola"],["Crema de zanahoria","Espagueti blanco","Pollo en salsa verde con nopales y champiñones",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta en almíbar"],["Licuado de fresa",null,"Molletes","Pico de gallo",null,null,"Café","Yogurt\nFruta"]],
   "38":[["Atole de avena",null,"Enjitomatadas de pavo","Lechuga, crema y queso","Frijoles refritos",null,"Té de hojas de naranjo","Yogurt con granola"],["Sopa de alberjón","Arroz blanco con plátano","Cerdo estilo minero",null,null,"Tortilla","Agua de fruta","Paleta de yogurt (industrias)"],["Leche","Cereal","Mortadela empanizada","Salsa roja\nEnsalada de lechuga con zanahoria","Frijoles guisados","Tortilla","Te de manzanilla","Fruta"]],
   "39":[["Leche sabor chocolate",null,"Sándwich de jamón y queso","Lechuga, jitomate, cebolla, chile, mayonesa, aguacate","Frijoles refritos","Totopos","Té de limón","Gelatina"],["Sopa de chayote","Arroz rojo","Conejo adobado horneado","Lechuga con pepino, cebolla y chile habanero","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Burritos de jamón con queso con frijoles molidos","Salsa chipotle\nEnsalada de lechuga con pepino",null,null,"Café","Fruta"]],
   "40":[["Leche","Repostería","Carne molida con nopales","Salsa roja","Frijoles guisados","Tortilla","Café","Fruta"],["Sopa de verduras","Codito rojo","Filete de pescado empanizado","Lechuga, zanahoria y betabel rallado, salsa valentina, limón","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Licuado de fruta",null,"Espagueti a la boloñesa",null,"Frijoles guisados","Baguette","Té de ponche de frutas","Ensalada dulce de col, zanahoria y piña"]],
   "41":[["Leche","Cereal","Huevo con tocino","Salsa roja","Frijoles guisados","Tortilla","Té de limón","Fruta"],["Consomé con verduras sin mollejas","Arroz blanco","Mole verde con pollo",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Longaniza con papas y nopales","Salsa de chile de árbol","Frijoles refritos","Tortilla","Té de limón","Charritos Quali"]],
   "42":[["Atole de amaranto",null,"Tamales de rajas y salsa verde",null,"Frijoles refritos","Totopos","Café","Jugo tetra pack\nFruta"],[null,"Arroz blanco","Bistec encebollado con papas","Salsa verde\nEnsalada de lechuga, pepino y limón","Frijoles guisados","Tortilla","Agua de fruta","Helado de crema en vaso"],["Leche","Pan tostado c/mermelada","Quesadillas de queso Oaxaca","Salsa ranchera, lechuga, crema","Frijoles guisados",null,"Té de hierbabuena","Fruta"]],
   "43":[["Leche\nYogurt y granola",null,"Marinas de pollo con mole",null,"Frijoles refritos c/queso",null,"Café","Fruta"],["Sopa de champiñones","Arroz blanco","Birria de res","Cebolla y chile picado, limón","Frijoles de la olla","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Sincronizada de maíz","Pico de gallo, aguacate, lechuga con pepino","Frijoles refritos",null,"Café","Gelatina"]],
   "44":[["Leche","Cereal","Burritos de jamón y queso con frijoles molidos","Salsa ranchera",null,null,"Té de hojas de limón","Fruta"],["Consomé con verduras y mollejas","Codito blanco","Pollo en cazuela de adobo",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Atole vainilla",null,"Pastel de papa con chorizo","Salsa verde cocida","Frijoles molidos","Tortilla","Te de canela","Fruta"]],
   "45":[["Leche",null,"Queso empanizado","Salsa chipotle, lechuga","Frijoles refritos","Tortilla","Café","Yogurt con granola"],[null,"Arroz blanco","Pierna enchilada con papas y salsa ranchera guisada","Ensalada de lechuga, pepino, zanahoria, limón","Frijoles de la olla","Tortilla","Agua de fruta","Paleta de crema"],["Café con leche",null,"Calabacitas a la mantequilla","Salsa roja, crema","Frijoles guisados","Tortilla","Té de frutas","Fruta\nKínder Delice"]],
   "46":[["Leche","Yakult","Huevo con coliflor","Salsa roja","Frijoles guisados","Tortilla","Café","Fruta"],["Ensalada rusa","Arroz rojo","Pastel de carne","Salsa roja\nLimón","Frijoles guisados","Baguette","Agua de fruta","Fruta"],["Leche","Cereal","Quesadillas de queso con espinacas","Salsa de chile de árbol, ensalada dulce de zanahoria rallada, betabel rallado, piña, nuez y pasas","Frijoles guisados",null,"Té de hierbabuena","Fruta"]],
   "47":[["Leche","Cereal","Picadillo de res","Chiles en vinagre","Frijoles guisados","Tortilla","Café","Fruta\nChocohojuelas"],[null,"Codito rojo","Conejo veloz","Lechuga con pepino, limones, salsa verde con chile habanero","Frijoles guisados con chorizo","Tortilla","Agua de fruta","Fruta en almíbar"],["Leche","Barrita","Tortitas de pollo en salsa verde con calabacitas","Ensalada de espinaca con tocino frito, ajonjolí y aceite de oliva.","Frijoles refritos","Tortilla","Café","Fruta"]],
   "48":[["Café con leche","Pan dulce","Huevo con papas","Salsa roja","Frijoles guisados","Tortilla","Té de frutas","Fruta"],["Sopa de verduras","Arroz rojo","Pollo en crema de chipotle con champiñones",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Cereal","Hot-dog","Jitomate, cebolla y chile picados, cátsup, mostaza y mayonesa","Frijoles refritos","otopos","Té de canela","Fruta"]],
   "49":[["Malteada de fresa",null,"Sopa azteca con bistec","Queso, crema","Frijoles de la olla",null,"Té de manzanilla","Fruta\nJugo tetra pack"],[null,"Arroz blanco","Pavo en mole rojo",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche","Arroz con leche","Quesadillas de horiqueso","Salsa roja cocida, lechuga, jitomate","Frijoles guisados",null,"Té de manzanilla","fruta"]],
   "50":[["Licuado de guayaba",null,"Quesadillas de queso panela y oaxaca con champiñones","Salsa ranchera lechuga y crema","Frijoles guisados",null,"Café","Yogurt con granola"],["Sopa de coliflor, brócoli y zanahoria","Arroz blanco","Estofado de res",null,"Frijoles de olla","Tortilla","Agua de fruta","Fruta"],["Café con leche","Repostería","Salpicón de pollo","Chiles curados, crema, queso","Frijoles refritos","Tostadas","Té de limón","Fruta"]],
   "51":[["Leche",null,"Huevo con jamón","Salsa chipotle","Frijoles refritos con queso","Tortilla","Té de fruta","Cereal de arroz inflado sabor chocolate"],["Sopa de papa","Arroz amarillo","Albóndigas de pollo en salsa verde",null,"Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche sabor vainilla",null,"Pambazos de papas con longaniza bañados en salsa de guajillo.","Queso, crema, salsa verde guisada y lechuga","Frijoles refritos",null,"Té de fruta","Fruta\nGelatina"]],
   "52":[["Malteada de chocolate","Yogurt c/granola","Chilaquiles verdes con pollo","Queso, crema","Frijoles refritos","Baguette","Café","Fruta"],["Sopa de pasta","Arroz blanco","Cecina de res","Guacamole, limones y nopales","Frijoles guisados","Tortilla","Agua de fruta","Fruta"],["Leche",null,"Huevo con pimiento y brócoli","Salsa roja cocida","Frijoles guisados","Tortilla","Café","Gelatina de leche\nFruta"]],
   "53":[["Leche","Cereal","Chuleta a la cacerola con verduras en salsa roja","Salsa ",null,"Frijoles guisados","Tortilla","Té de azahares"],[null,"Codito rojo","Tortita de atún con zanahoria en salsa verde con nopales",null,"Frijoles refritos con chorizo","Tortilla","Agua de fruta","Fresas congeladas con crema"],["Leche",null,"Pozole rojo de cerdo","Chile piquín molido, orégano, lechuga, rábano, cebolla aguacate y limón","Frijoles refritos","Tostadas","Café","Fruta"]],
   "54":[["Café con leche","Pan dulce","Pollo con espinacas en salsa verde",null,"Frijoles guisados","Tortilla","Té de hojas de guayabo","Fruta"],["Sopa de verduras","Arroz rojo","Ceviche con pescado, pulpo y camarón","Lechuga, pepino, jitomate, limón, aguacate, valentina","Frijoles guisados","Tostadas","Agua de Fruta","Fruta"],["Leche","Cereal","Memelas campechanas","Queso, crema, lechuga, salsa roja cocida","Frijoles refritos",null,"Té de frutas","Fruta"]],
   "55":[["Leche",null,"Huevo con chorizo","Salsa ranchera","Frijoles guisados","Tortilla","Té de canela","Fruta\nGomita de nopal enchilado"],["Consomé con verduras","Arroz blanco","Pollo en chile pasilla",null,"Frijoles guisados","Tortilla","Agua de Fruta","Paleta de yogurt (industrias)"],["Leche","Arroz con leche","Tacos dorados de pollo","Lechuga, salsa verde cocida, crema y queso","Frijoles refritos",null,"Té de limón","Fruta"]],
   "56":[["Malteada de fresa",null,"Enmoladas con queso","Queso, crema, lechuga","Frijoles de la olla",null,"Té de mananilla","Fruta\nJugo tetra pack"],["Crema de eleote","Espagueti rojo","Verduras a la mantequilla, gratinadas con fajitas de pollo","Salsa roja","Frijoles guisados","Tortilla","Agua de fruta","Duraznos en almíbar"],["Leche",null,"Pastel azteca","Salsa roja","Frijoles guisados","Baguette","Café","Fruta\nRocko"]]
  };

  static final inicio = DateTime(2019, 1, 21);
  static final fin = DateTime(2019, 6, 23);

  static const lastUpdateMenu = 2019012901; 
  static const lastUpdateFechas = 2019011602;

  static const bool legacy = true;

  static const info = <String, dynamic>{
    "20190120": {
      "title": "Sólo cena, sólo central",
      "subtitle": "(Nota: Ésta puede variar)",
      "icon": 57346,
      "url": "https://www.facebook.com/352113288318243/posts/901678500028383"
    },
    "20190121": {
      "title": "Desayuno sólo en el central",
      "subtitle": "Toca para ver la publicación de Servicios Asistenciales",
      "icon": 57346,
      "url": "https://www.facebook.com/352113288318243/posts/901678500028383"
    }
  };

  static const lastUpdateInfo = 2019011704;
}
